name: Test GitHub Token

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
    - name: Check if GitHub Token exists
      run: |
        echo "Token exists: ${{ secrets.GITHUB_TOKEN != '' }}"
        echo "Token length: ${#GITHUB_TOKEN}"
        echo "Token starts with: ${GITHUB_TOKEN:0:10}..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Use token to call GitHub API
      run: |
        echo "Testing API call with token..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/user 